/*
 * Copyright (c) 2023. Knight Hat
 * All rights reserved.
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package me.knighthat.interactivedeck.menus.modifier;

import me.knighthat.interactivedeck.component.ibutton.IButton;
import org.jetbrains.annotations.NotNull;

/**
 *
 * @author knighthat
 */
public class TaskModifierPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaskModifierPanel
     */
    public TaskModifierPanel() {
        initComponents();
    }
    
    public TaskModifierPanel(@NotNull IButton selected) {
        this();
        this.selected = selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JPanel runScriptTaskPanel = new javax.swing.JPanel();
        javax.swing.JRadioButton runScriptLabel = new javax.swing.JRadioButton();
        runScriptInput = new javax.swing.JTextField();
        javax.swing.JPanel gotoTaskPanel = new javax.swing.JPanel();
        javax.swing.JRadioButton gotoLabel = new javax.swing.JRadioButton();
        gotoList = new javax.swing.JComboBox<>();
        applyButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 36, 36));
        setMaximumSize(new java.awt.Dimension(250, 489));
        setMinimumSize(new java.awt.Dimension(250, 489));
        setLayout(new java.awt.GridBagLayout());

        runScriptTaskPanel.setMaximumSize(new java.awt.Dimension(250, 200));
        runScriptTaskPanel.setMinimumSize(new java.awt.Dimension(250, 200));
        runScriptTaskPanel.setOpaque(false);
        runScriptTaskPanel.setPreferredSize(new java.awt.Dimension(250, 200));
        runScriptTaskPanel.setLayout(new java.awt.GridBagLayout());

        runScriptLabel.setForeground(new java.awt.Color(255, 255, 255));
        runScriptLabel.setText("Run script");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        runScriptTaskPanel.add(runScriptLabel, gridBagConstraints);

        runScriptInput.setMaximumSize(new java.awt.Dimension(200, 40));
        runScriptInput.setMinimumSize(new java.awt.Dimension(200, 40));
        runScriptInput.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        runScriptTaskPanel.add(runScriptInput, gridBagConstraints);

        add(runScriptTaskPanel, new java.awt.GridBagConstraints());

        gotoTaskPanel.setMaximumSize(new java.awt.Dimension(250, 200));
        gotoTaskPanel.setMinimumSize(new java.awt.Dimension(250, 200));
        gotoTaskPanel.setOpaque(false);
        gotoTaskPanel.setPreferredSize(new java.awt.Dimension(250, 200));
        gotoTaskPanel.setLayout(new java.awt.GridBagLayout());

        gotoLabel.setForeground(new java.awt.Color(255, 255, 255));
        gotoLabel.setText("Go To Page");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        gotoTaskPanel.add(gotoLabel, gridBagConstraints);

        gotoList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gotoList.setMaximumSize(new java.awt.Dimension(200, 40));
        gotoList.setMinimumSize(new java.awt.Dimension(200, 40));
        gotoList.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gotoTaskPanel.add(gotoList, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(gotoTaskPanel, gridBagConstraints);

        applyButton.setText("Apply");
        applyButton.setMaximumSize(new java.awt.Dimension(140, 30));
        applyButton.setMinimumSize(new java.awt.Dimension(140, 30));
        applyButton.setPreferredSize(new java.awt.Dimension(140, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(applyButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JComboBox<String> gotoList;
    private javax.swing.JTextField runScriptInput;
    // End of variables declaration//GEN-END:variables
    private @NotNull IButton selected;
}
