/*
 * Copyright (c) 2023. Knight Hat
 * All rights reserved.
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package me.knighthat.interactivedeck.menus.modifier;

import java.io.File;
import javax.swing.JRadioButton;
import me.knighthat.interactivedeck.component.ibutton.IButton;
import me.knighthat.interactivedeck.connection.request.Request;
import me.knighthat.interactivedeck.connection.request.UpdateRequest;
import me.knighthat.interactivedeck.connection.wireless.WirelessSender;
import me.knighthat.interactivedeck.console.Log;
import me.knighthat.interactivedeck.file.Profile;
import me.knighthat.interactivedeck.menus.MenuProperty;
import me.knighthat.interactivedeck.task.BashExecutor;
import me.knighthat.interactivedeck.task.GotoPage;
import me.knighthat.interactivedeck.task.Task;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 *
 * @author knighthat
 */
public class TaskModifierPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaskModifierPanel
     */
    public TaskModifierPanel() {
        initComponents();
    }
    
    public TaskModifierPanel(@NotNull IButton selected) {
        this();
        this.selected = selected;
        
        loadButtonTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JPanel runScriptTaskPanel = new javax.swing.JPanel();
        runScriptButton = new javax.swing.JRadioButton();
        runScriptInput = new javax.swing.JTextField();
        javax.swing.JPanel gotoTaskPanel = new javax.swing.JPanel();
        gotoButton = new javax.swing.JRadioButton();
        profilesList = new me.knighthat.interactivedeck.component.plist.ProfilesComboBox();
        applyButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 36, 36));
        setMaximumSize(new java.awt.Dimension(250, 489));
        setMinimumSize(new java.awt.Dimension(250, 489));
        setLayout(new java.awt.GridBagLayout());

        runScriptTaskPanel.setMaximumSize(new java.awt.Dimension(250, 200));
        runScriptTaskPanel.setMinimumSize(new java.awt.Dimension(250, 200));
        runScriptTaskPanel.setOpaque(false);
        runScriptTaskPanel.setPreferredSize(new java.awt.Dimension(250, 200));
        runScriptTaskPanel.setLayout(new java.awt.GridBagLayout());

        runScriptButton.setForeground(new java.awt.Color(255, 255, 255));
        runScriptButton.setText("Run script");
        runScriptButton.addItemListener(event -> {
            JRadioButton source = (JRadioButton) event.getItem();
            this.buttonStateChange(source);
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        runScriptTaskPanel.add(runScriptButton, gridBagConstraints);

        runScriptInput.setMaximumSize(new java.awt.Dimension(200, 40));
        runScriptInput.setMinimumSize(new java.awt.Dimension(200, 40));
        runScriptInput.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        runScriptTaskPanel.add(runScriptInput, gridBagConstraints);

        add(runScriptTaskPanel, new java.awt.GridBagConstraints());

        gotoTaskPanel.setMaximumSize(new java.awt.Dimension(250, 200));
        gotoTaskPanel.setMinimumSize(new java.awt.Dimension(250, 200));
        gotoTaskPanel.setOpaque(false);
        gotoTaskPanel.setPreferredSize(new java.awt.Dimension(250, 200));
        gotoTaskPanel.setLayout(new java.awt.GridBagLayout());

        gotoButton.setForeground(new java.awt.Color(255, 255, 255));
        gotoButton.setText("Go To Page");
        gotoButton.addItemListener(event -> {
            JRadioButton source = (JRadioButton) event.getItem();
            this.buttonStateChange(source);
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        gotoTaskPanel.add(gotoButton, gridBagConstraints);

        profilesList.setMaximumSize(new java.awt.Dimension(200, 40));
        profilesList.setMinimumSize(new java.awt.Dimension(200, 40));
        profilesList.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gotoTaskPanel.add(profilesList, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(gotoTaskPanel, gridBagConstraints);

        applyButton.setText("Apply");
        applyButton.setMaximumSize(new java.awt.Dimension(140, 30));
        applyButton.setMinimumSize(new java.awt.Dimension(140, 30));
        applyButton.setPreferredSize(new java.awt.Dimension(140, 30));
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyButtonClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(applyButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonClicked
       Task task = null;
        
        if (this.gotoButton.isSelected())
            task = createGotoPageTask();
        if (this.runScriptButton.isSelected())
            task = createBashExecutorTask();
        
        this.selected.task(task);
        
        Request request = new UpdateRequest(this.selected);
        WirelessSender.send(request);        
    }//GEN-LAST:event_applyButtonClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JRadioButton gotoButton;
    private me.knighthat.interactivedeck.component.plist.ProfilesComboBox profilesList;
    private javax.swing.JRadioButton runScriptButton;
    private javax.swing.JTextField runScriptInput;
    // End of variables declaration//GEN-END:variables
    private @NotNull IButton selected;
    
    private void loadButtonTask() {
        Task task = selected.task();
        if (task instanceof BashExecutor executor) {
            this.runScriptButton.setSelected( true );
            this.runScriptInput.setText( executor.path() );
        } else if (task instanceof GotoPage gotoPage) {
            this.gotoButton.setSelected( true );

            Profile profile =
                        MenuProperty
                        .profile( gotoPage.target() )
                        .orElse(MenuProperty.active());
            this.profilesList.setSelectedItem( profile.displayName() );
        }
    }
    
    private void buttonStateChange(@NotNull JRadioButton source) {
        if (source.isSelected()) {
            if (source == runScriptButton ) {
                this.runScriptInput.setEnabled(true);
                this.profilesList.setEnabled(false);
                this.gotoButton.setSelected(false);
            } else if (source == gotoButton) {
                this.profilesList.setEnabled(true);
                this.runScriptInput.setEnabled(false);
                this.runScriptButton.setSelected(false);
            }
        } else {
            if (source == runScriptButton ) {
                this.runScriptInput.setEditable(false);
            } else if (source == gotoButton) {
                this.profilesList.setEditable(false);
            }
        }
    }
    
    private @Nullable Task createGotoPageTask() {
        String selected = (String) this.profilesList.getSelectedItem();

        Task task = null;
        for (Profile profile : MenuProperty.profiles())
        if (profile.displayName().equals( selected )) {
                task = new GotoPage( profile.uuid );
                break;
        }
        return task;
    }

    private @Nullable Task createBashExecutorTask() {
        String filePath = this.runScriptInput.getText();
        if (filePath.isBlank()) return null;

        File file = new File( filePath );
        if (!file.exists()) {
            Log.err("File \"" + file.getAbsolutePath() + "\" does NOT exist!");
            return null;
        }
        return  new BashExecutor( file );
    }
}
