/*
 * Copyright (c) 2023. Knight Hat
 * All rights reserved.
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package me.knighthat.interactivedeck.menus.modifier;

import me.knighthat.interactivedeck.component.ibutton.IButton;
import org.jetbrains.annotations.NotNull;

/**
 * @author knighthat
 */
public class TextModifierPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JToggleButton boldButton;
    private javax.swing.JComboBox<String> fontSelector;
    private javax.swing.JSpinner fontSizeSpinner;
    private javax.swing.JToggleButton italicButton;
    private javax.swing.JTextField titleInput;
    private javax.swing.JToggleButton underlineButton;
    // End of variables declaration//GEN-END:variables
    private IButton selected;

    /**
     * Creates new form TextModifierPanel
     */
    public TextModifierPanel() {
        initComponents();
    }

    public TextModifierPanel( @NotNull IButton selected ) {
        this();
        this.selected = selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JLabel titleLabel = new javax.swing.JLabel();
        titleInput = new javax.swing.JTextField();
        fontSelector = new javax.swing.JComboBox<>();
        fontSizeSpinner = new javax.swing.JSpinner();
        boldButton = new javax.swing.JToggleButton();
        italicButton = new javax.swing.JToggleButton();
        underlineButton = new javax.swing.JToggleButton();
        applyButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 36, 36));
        setMaximumSize(new java.awt.Dimension(250, 489));
        setMinimumSize(new java.awt.Dimension(250, 489));
        setPreferredSize(new java.awt.Dimension(250, 489));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {70, 70, 70};
        setLayout(layout);

        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Label");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(titleLabel, gridBagConstraints);

        titleInput.setMaximumSize(new java.awt.Dimension(140, 40));
        titleInput.setMinimumSize(new java.awt.Dimension(140, 40));
        titleInput.setPreferredSize(new java.awt.Dimension(140, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(titleInput, gridBagConstraints);

        fontSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fontSelector.setMaximumSize(new java.awt.Dimension(140, 30));
        fontSelector.setMinimumSize(new java.awt.Dimension(140, 30));
        fontSelector.setPreferredSize(new java.awt.Dimension(140, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(fontSelector, gridBagConstraints);

        fontSizeSpinner.setMaximumSize(new java.awt.Dimension(55, 30));
        fontSizeSpinner.setMinimumSize(new java.awt.Dimension(55, 30));
        fontSizeSpinner.setPreferredSize(new java.awt.Dimension(55, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(fontSizeSpinner, gridBagConstraints);

        boldButton.setText("B");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(boldButton, gridBagConstraints);

        italicButton.setText("I");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(italicButton, gridBagConstraints);

        underlineButton.setText("U");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        add(underlineButton, gridBagConstraints);

        applyButton.setText("Apply");
        applyButton.setMaximumSize(new java.awt.Dimension(140, 30));
        applyButton.setMinimumSize(new java.awt.Dimension(140, 30));
        applyButton.setPreferredSize(new java.awt.Dimension(140, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        add(applyButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
}
