/*
 * Copyright (c) 2023. Knight Hat
 * All rights reserved.
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package me.knighthat.interactivedeck.menus;

import me.knighthat.interactivedeck.component.ibutton.IButton;
import me.knighthat.interactivedeck.menus.modifier.IconModifierPanel;
import me.knighthat.interactivedeck.menus.modifier.TaskModifierPanel;
import me.knighthat.interactivedeck.menus.modifier.TextModifierPanel;
import org.jetbrains.annotations.NotNull;

/**
 * @author knighthat
 */
public class ButtonModifierPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private final @NotNull IButton selected;

    public ButtonModifierPanel( @NotNull IButton selected ) {
        this.selected = selected;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTabbedPane modifierTabbedPane = new javax.swing.JTabbedPane();
        me.knighthat.interactivedeck.menus.modifier.TextModifierPanel textModifier = new TextModifierPanel(selected);
        me.knighthat.interactivedeck.menus.modifier.IconModifierPanel iconModifier = new IconModifierPanel(selected);
        me.knighthat.interactivedeck.menus.modifier.TaskModifierPanel taskModifier = new TaskModifierPanel(selected);

        setMaximumSize(new java.awt.Dimension(250, 520));
        setMinimumSize(new java.awt.Dimension(250, 520));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(250, 520));
        setLayout(new java.awt.BorderLayout());

        modifierTabbedPane.setBackground(new java.awt.Color(36, 36, 36));
        modifierTabbedPane.addTab("Text", textModifier);
        modifierTabbedPane.addTab("Icon", iconModifier);
        modifierTabbedPane.addTab("Task", taskModifier);

        add(modifierTabbedPane, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

}
