/*
 * Copyright (c) 2023. Knight Hat
 * All rights reserved.
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package me.knighthat.interactivedeck.menus;

import java.awt.Color;
import java.awt.KeyboardFocusManager;
import me.knighthat.interactivedeck.ui.customs.StatusIndicator;
import me.knighthat.interactivedeck.utils.ColorConverter;
import me.knighthat.interactivedeck.utils.GlobalVars;

/**
 *
 * @author knighthat
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        super(GlobalVars.name() + " - " + GlobalVars.version());
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        profilesSection = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnLayoutSection = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnContainer = new javax.swing.JPanel();
        btnContainer.setBackground(new Color(0,0,0,0));
        iBtn1 = new javax.swing.JButton();
        iBtn2 = new javax.swing.JButton();
        iBtn3 = new javax.swing.JButton();
        iBtn4 = new javax.swing.JButton();
        iBtn5 = new javax.swing.JButton();
        iBtn6 = new javax.swing.JButton();
        iBtn7 = new javax.swing.JButton();
        iBtn8 = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnModifierSection = new javax.swing.JPanel();
        iBtnName = new javax.swing.JTextField();
        iBtnFgColor = new javax.swing.JTextField();
        btnNameModifier = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iBtnBgColor = new javax.swing.JTextField();
        statusSection = new javax.swing.JPanel();
        indicator = new StatusIndicator(statusLabel);
        statusLabel = new javax.swing.JLabel();
        statusLabel.setText(((StatusIndicator) indicator).getStatus().getStatus());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        profilesSection.setBackground(new java.awt.Color(36, 36, 36));
        profilesSection.setPreferredSize(new java.awt.Dimension(1000, 50));

        jComboBox2.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(300, 30));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Add");
        jButton4.setAlignmentY(0.0F);
        jButton4.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Remove");
        jButton1.setAlignmentY(0.0F);
        jButton1.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Configure");
        jButton2.setAlignmentY(0.0F);
        jButton2.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout profilesSectionLayout = new javax.swing.GroupLayout(profilesSection);
        profilesSection.setLayout(profilesSectionLayout);
        profilesSectionLayout.setHorizontalGroup(
            profilesSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilesSectionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        profilesSectionLayout.setVerticalGroup(
            profilesSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilesSectionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(profilesSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(profilesSection, java.awt.BorderLayout.NORTH);

        btnLayoutSection.setBackground(new java.awt.Color(51, 51, 51));
        btnLayoutSection.setDoubleBuffered(false);
        btnLayoutSection.setPreferredSize(new java.awt.Dimension(750, 0));
        btnLayoutSection.setLayout(new java.awt.GridBagLayout());
        btnLayoutSection.add(filler1, new java.awt.GridBagConstraints());
        btnLayoutSection.add(filler2, new java.awt.GridBagConstraints());

        btnContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnContainer.setDoubleBuffered(false);
        btnContainer.setMaximumSize(new java.awt.Dimension(510, 250));
        btnContainer.setName(""); // NOI18N
        btnContainer.setPreferredSize(new java.awt.Dimension(510, 250));
        btnContainer.setLayout(new java.awt.GridLayout(2, 4, 5, 5));

        iBtn1.setText("IButton 1");
        iBtn1.setAlignmentY(0.0F);
        iBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iBtnClickEvent(evt);
            }
        });
        btnContainer.add(iBtn1);

        iBtn2.setText("IButton 2");
        iBtn2.setAlignmentY(0.0F);
        iBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iBtnClickEvent(evt);
            }
        });
        btnContainer.add(iBtn2);

        iBtn3.setText("IButton 3");
        iBtn3.setAlignmentY(0.0F);
        iBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iBtnClickEvent(evt);
            }
        });
        btnContainer.add(iBtn3);

        iBtn4.setText("IButton 4");
        iBtn4.setAlignmentY(0.0F);
        iBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iBtnClickEvent(evt);
            }
        });
        btnContainer.add(iBtn4);

        iBtn5.setText("IButton 5");
        iBtn5.setAlignmentY(0.0F);
        iBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iBtnClickEvent(evt);
            }
        });
        btnContainer.add(iBtn5);

        iBtn6.setText("IButton 6");
        iBtn6.setAlignmentY(0.0F);
        iBtn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iBtnClickEvent(evt);
            }
        });
        btnContainer.add(iBtn6);

        iBtn7.setText("IButton 7");
        iBtn7.setAlignmentY(0.0F);
        iBtn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iBtnClickEvent(evt);
            }
        });
        btnContainer.add(iBtn7);

        iBtn8.setText("IButton 8");
        iBtn8.setAlignmentY(0.0F);
        iBtn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iBtnClickEvent(evt);
            }
        });
        btnContainer.add(iBtn8);

        btnLayoutSection.add(btnContainer, new java.awt.GridBagConstraints());
        btnLayoutSection.add(filler4, new java.awt.GridBagConstraints());
        btnLayoutSection.add(filler3, new java.awt.GridBagConstraints());

        getContentPane().add(btnLayoutSection, java.awt.BorderLayout.WEST);

        btnModifierSection.setBackground(new java.awt.Color(36, 36, 36));
        btnModifierSection.setDoubleBuffered(false);
        btnModifierSection.setPreferredSize(new java.awt.Dimension(250, 0));
        btnModifierSection.setLayout(new java.awt.GridBagLayout());

        iBtnName.setBackground(new java.awt.Color(51, 51, 51));
        iBtnName.setForeground(new java.awt.Color(255, 255, 255));
        iBtnName.setText("Enter Name");
        iBtnName.setMinimumSize(new java.awt.Dimension(200, 30));
        iBtnName.setName(""); // NOI18N
        iBtnName.setPreferredSize(new java.awt.Dimension(200, 40));
        iBtnName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modifierFocusLostEvent(evt);
            }
        });
        iBtnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierEnterKeyPressedEvent(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        btnModifierSection.add(iBtnName, gridBagConstraints);

        iBtnFgColor.setBackground(new java.awt.Color(51, 51, 51));
        iBtnFgColor.setForeground(new java.awt.Color(255, 255, 255));
        iBtnFgColor.setText("Hex Color");
        iBtnFgColor.setPreferredSize(new java.awt.Dimension(200, 40));
        iBtnFgColor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modifierFocusLostEvent(evt);
            }
        });
        iBtnFgColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierEnterKeyPressedEvent(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        btnModifierSection.add(iBtnFgColor, gridBagConstraints);

        btnNameModifier.setForeground(new java.awt.Color(255, 255, 255));
        btnNameModifier.setText("Name");
        btnNameModifier.setToolTipText("Text display on the button");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        btnModifierSection.add(btnNameModifier, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Text Color");
        jLabel2.setToolTipText("Colorize display text");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        btnModifierSection.add(jLabel2, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Background Color");
        jLabel3.setToolTipText("Set background color for button");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        btnModifierSection.add(jLabel3, gridBagConstraints);

        iBtnBgColor.setBackground(new java.awt.Color(51, 51, 51));
        iBtnBgColor.setForeground(new java.awt.Color(255, 255, 255));
        iBtnBgColor.setText("Hex Color");
        iBtnBgColor.setPreferredSize(new java.awt.Dimension(200, 40));
        iBtnBgColor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modifierFocusLostEvent(evt);
            }
        });
        iBtnBgColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierEnterKeyPressedEvent(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        btnModifierSection.add(iBtnBgColor, gridBagConstraints);

        getContentPane().add(btnModifierSection, java.awt.BorderLayout.CENTER);

        statusSection.setBackground(new java.awt.Color(36, 36, 36));
        statusSection.setAlignmentX(0.0F);
        statusSection.setAlignmentY(0.0F);
        statusSection.setPreferredSize(new java.awt.Dimension(1000, 30));

        indicator.setMaximumSize(new java.awt.Dimension(30, 30));
        indicator.setMinimumSize(new java.awt.Dimension(30, 30));
        indicator.setPreferredSize(new java.awt.Dimension(15, 30));

        statusLabel.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setAlignmentY(0.0F);
        statusLabel.setMaximumSize(new java.awt.Dimension(100, 30));
        statusLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        statusLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout statusSectionLayout = new javax.swing.GroupLayout(statusSection);
        statusSection.setLayout(statusSectionLayout);
        statusSectionLayout.setHorizontalGroup(
            statusSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusSectionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(indicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(855, Short.MAX_VALUE))
        );
        statusSectionLayout.setVerticalGroup(
            statusSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusSectionLayout.createSequentialGroup()
                .addGroup(statusSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(statusSection, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void iBtnClickEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iBtnClickEvent
        javax.swing.JButton clicked = (javax.swing.JButton) evt.getComponent();
        setTarget(clicked);
    }//GEN-LAST:event_iBtnClickEvent

    private void modifierFocusLostEvent(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modifierFocusLostEvent
        javax.swing.JTextField modifier = (javax.swing.JTextField) evt.getComponent();
        updateButton(modifier);
    }//GEN-LAST:event_modifierFocusLostEvent

    private void modifierEnterKeyPressedEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierEnterKeyPressedEvent
        java.awt.Component component = KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
        updateButton((javax.swing.JTextField) component);
    }//GEN-LAST:event_modifierEnterKeyPressedEvent


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnContainer;
    private javax.swing.JPanel btnLayoutSection;
    private javax.swing.JPanel btnModifierSection;
    private javax.swing.JLabel btnNameModifier;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton iBtn1;
    private javax.swing.JButton iBtn2;
    private javax.swing.JButton iBtn3;
    private javax.swing.JButton iBtn4;
    private javax.swing.JButton iBtn5;
    private javax.swing.JButton iBtn6;
    private javax.swing.JButton iBtn7;
    private javax.swing.JButton iBtn8;
    private javax.swing.JTextField iBtnBgColor;
    private javax.swing.JTextField iBtnFgColor;
    private javax.swing.JTextField iBtnName;
    private javax.swing.JLabel indicator;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel profilesSection;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusSection;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JButton target;
    
    public void setTarget(javax.swing.JButton target) {
        this.target = target;
        iBtnName.setText(target.getText());
        
        Color fgColor = target.getForeground();
        String fgHex = ColorConverter.toHex(fgColor);
        iBtnFgColor.setText(fgHex);
        iBtnFgColor.setBackground(fgColor);
        
        
        Color bgColor = target.getBackground();
        String bgHex = ColorConverter.toHex(bgColor);
        iBtnBgColor.setText(bgHex);
        iBtnBgColor.setBackground(bgColor);
    }
    
    void updateButton(javax.swing.JTextField modifier) {
        if (target == null) return;
        
        String content = modifier.getText();        
        
        if (modifier == iBtnName) {
            
            target.setText(content);
            
        } else if (modifier == iBtnFgColor) {
            
            Color fg = ColorConverter.parse(content);
            target.setForeground(fg);
            modifier.setBackground(fg);
            
        } else if (modifier == iBtnBgColor) {
            
            Color bg = ColorConverter.parse(content);
            target.setBackground(bg);
            modifier.setBackground(bg);
            
        }  
    }
}
